In [117]:
import numpy as np
import xarray as xr
import pandas as pd
import glob

In [104]:
outputs_l1 = glob.glob('../outputs/surr/*tau1.csv')
outputs_l3 = glob.glob('../outputs/surr/*tau3.csv')
outputs_l6 = glob.glob('../outputs/surr/*tau6.csv')

In [109]:
surr_l1_df = pd.DataFrame()
for i in range(len(outputs_l1)):
    df = pd.read_csv(outputs_l1[i])
    surr_l1_df = pd.concat([surr_l1_df, df], axis=0)

In [113]:
surr_l3_df = pd.DataFrame()
for i in range(len(outputs_l3)):
    df = pd.read_csv(outputs_l3[i])
    surr_l3_df = pd.concat([surr_l3_df, df], axis=0)

In [114]:
surr_l6_df = pd.DataFrame()
for i in range(len(outputs_l6)):
    df = pd.read_csv(outputs_l6[i])
    surr_l6_df = pd.concat([surr_l6_df, df], axis=0)

In [121]:
np.percentile(surr_l1_df['rho'], [2.5, 97.5])

array([-0.038   ,  0.140025])

In [122]:
np.percentile(surr_l3_df['rho'], [2.5, 97.5])

array([-0.022   ,  0.211025])

In [123]:
np.percentile(surr_l6_df['rho'], [2.5, 97.5])

array([-0.013025,  0.250025])

In [129]:
surr_l1_df['rho'].mean()

0.038005000000000004

In [130]:
surr_l3_df['rho'].mean()

0.06865083333333333

In [131]:
surr_l6_df['rho'].mean()

0.07691